### ISSUE TITLE
Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by kjitender469** [felHR85/UsbSerial#206]
2019-02-12 19:00:55.593 27081-27081/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jitu.testingapp, PID: 27081
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.jitu.testingapp/com.example.jitu.testingapp.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.jitu.testingapp.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/base.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.jitu.testingapp.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/base.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
2019-02-12 19:00:55.598 27081-27081/? E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1178)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3082)
        	... 9 more
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 12 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/base.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
    		Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_dependencies_apk.apk because: Failure to verify dex file '/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_dependencies_apk.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
        at android.app.LoadedApk.getResources(LoadedApk.java:996)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6398)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
2019-02-12 19:00:55.603 27081-27081/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        			... 6 more
    		Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
        at android.app.LoadedApk.getResources(LoadedApk.java:996)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6398)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        			... 6 more
    		Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_8_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
        at android.app.LoadedApk.getResources(LoadedApk.java:996)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6398)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        			... 6 more
    	[CIRCULAR REFERENCE:java.io.IOException: Failed to open dex files from /data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_dependencies_apk.apk because: Failure to verify dex file '/data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_dependencies_apk.apk': Bad method handle type 7]
    	[CIRCULAR REFERENCE:java.io.IOException: No original dex files found for dex location /data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_resources_apk.apk]
    	[CIRCULAR REFERENCE:java.io.IOException: No original dex files found for dex location /data/app/com.example.jitu.testingapp-vyV0H4XZnoSIlg_abBJwnQ==/split_lib_slice_8_apk.apk]

**Comment by felHR85** [comment]
Doesnt look like a UsbSerial problem
